# Generated by Django 6.0.2 on 2026-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filter_name',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
